### ISSUE TITLE
ExportToJson returns NULL without setting an error

### ISSUE THREAD

**Issue by reinvantveer** [reinvantveer/edna-ld#1]
```
Percent: [#######---]      72.23%  - Processing file /data/EDNA-LD_EXT/easy_rest/downloads/34198/2007241_Hoogteverschil.mifWarning 1: Infinite or NaN coordinate encountered
Traceback (most recent call last):
  File "main.py", line 164, in <module>
    run(file_path)
  File "main.py", line 86, in run
    data = MIFparser.to_dict(file)
  File "/home/rein/Documents/git/edna-ld/etl/lib/MIFparser.py", line 42, in to_dict
    geojson = feature.ExportToJson()
  File "/home/rein/.pyenv/versions/3.5.3/lib/python3.5/site-packages/osgeo/ogr.py", line 4876, in ExportToJson
    geom_json_string = geom.ExportToJson(options = options)
  File "/home/rein/.pyenv/versions/3.5.3/lib/python3.5/site-packages/osgeo/ogr.py", line 6243, in ExportToJson
    return _ogr.Geometry_ExportToJson(self, *args, **kwargs)
SystemError: <built-in function Geometry_ExportToJson> returned NULL without setting an error
```

**Comment by reinvantveer** [comment]
Fixed
